[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
rest = { path = "../rest" }

anyhow.workspace = true
serde = { workspace = true }
serde_json = { workspace = true }

clap = { version = "4.5.52", features = ["derive"] }
ureq = { version = "3.1.4", features = ["json"] }
