[package]
name = "rest"
version = "0.1.0"
edition = "2024"

[dependencies]
tiny_http = "0.12.0"
tokio = { version = "1.48.0", features = ["full"] }

anyhow.workspace = true
serde = { workspace = true }
serde_json = { workspace = true }
